name: Release

on:
  push:
    tags: [ * ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make dep

    - name: Build
      run: make build 

    - name: Docker Build
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        make docker_image
        docker tag devops/pinger:latest devops/pinger:${{ steps.vars.outputs.tag }}
	make docker_tar

    - uses: actions/upload-artifact@v2
      with:
        name: pinger
        path: cmd/pinger
     
    - uses: actions/upload-artifact@v2
      with:
        name: docker_tar
        path: build/pinger.tar
        
